# Generated by Django 3.2.8 on 2022-10-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0002_questionbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='answers',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
