# Generated by Django 3.2.8 on 2022-10-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0003_contestant_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='answers',
        ),
    ]
