# Generated by Django 3.2.8 on 2022-10-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0004_remove_contestant_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='score',
            field=models.IntegerField(default=0, max_length=3),
            preserve_default=False,
        ),
    ]
