# Generated by Django 3.2.8 on 2022-10-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz1', '0007_alter_contestant_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='uid',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contestant',
            name='score',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
